import * as THREE from 'three';

export const SHARED_BUILDING_MATS = {
  timberDark: new THREE.MeshStandardMaterial({ color: '#3d2614', roughness: 0.9, flatShading: true }),
  timberMed: new THREE.MeshStandardMaterial({ color: '#54361e', roughness: 0.88, flatShading: true }),
  timberLight: new THREE.MeshStandardMaterial({ color: '#784c28', roughness: 0.85, flatShading: true }),
  plaster: new THREE.MeshStandardMaterial({ color: '#e2d7c5', roughness: 0.92, flatShading: true }),
  stoneDark: new THREE.MeshStandardMaterial({ color: '#3f495a', roughness: 0.9, flatShading: true }),
  stoneMed: new THREE.MeshStandardMaterial({ color: '#526071', roughness: 0.88, flatShading: true }),
  stoneLight: new THREE.MeshStandardMaterial({ color: '#68798d', roughness: 0.85, flatShading: true }),
  thatchRoof: new THREE.MeshStandardMaterial({ color: '#92400e', roughness: 0.9, flatShading: true }),
  shingleRoof: new THREE.MeshStandardMaterial({ color: '#7c2d12', roughness: 0.85, flatShading: true }),
  royalBlueRoof: new THREE.MeshStandardMaterial({ color: '#1e3a8a', roughness: 0.85, flatShading: true }),
  awningGreen: new THREE.MeshStandardMaterial({ color: '#15803d', roughness: 0.7, flatShading: true }),
  awningWhite: new THREE.MeshStandardMaterial({ color: '#f8fafc', roughness: 0.7, flatShading: true }),
  goldWheat: new THREE.MeshStandardMaterial({ color: '#eab308', roughness: 0.8, flatShading: true }),
  richSoil: new THREE.MeshStandardMaterial({ color: '#2b1b11', roughness: 0.95, flatShading: true }),
  fireOrange: new THREE.MeshBasicMaterial({ color: '#f97316' }),
  fireYellow: new THREE.MeshBasicMaterial({ color: '#fde047' }),
  smokeWhite: new THREE.MeshStandardMaterial({ color: '#cbd5e1', transparent: true, opacity: 0.45, roughness: 1.0, flatShading: true }),
  scaffolding: new THREE.MeshStandardMaterial({ color: '#854d0e', roughness: 0.9, flatShading: true }),
  blueprintGhost: new THREE.MeshStandardMaterial({ color: '#38bdf8', transparent: true, opacity: 0.35, roughness: 0.5 }),
  redBanner: new THREE.MeshStandardMaterial({ color: '#b91c1c', roughness: 0.8, flatShading: true }),
  goldTrim: new THREE.MeshStandardMaterial({ color: '#fbbf24', roughness: 0.4, metalness: 0.3, flatShading: true }),
  tentFabric: new THREE.MeshStandardMaterial({ color: '#c28b58', roughness: 0.9, flatShading: true }),
  tentBedroll: new THREE.MeshStandardMaterial({ color: '#7c3aed', roughness: 0.85, flatShading: true }),
  sawBlade: new THREE.MeshStandardMaterial({ color: '#94a3b8', roughness: 0.3, metalness: 0.7, flatShading: true }),
  axeBlade: new THREE.MeshStandardMaterial({ color: '#64748b', roughness: 0.35, metalness: 0.6, flatShading: true }),
  woodShavings: new THREE.MeshStandardMaterial({ color: '#ca8a04', roughness: 0.95, flatShading: true }),
  bedLinenRed: new THREE.MeshStandardMaterial({ color: '#b91c1c', roughness: 0.85, flatShading: true }),
  bedLinenBlue: new THREE.MeshStandardMaterial({ color: '#1d4ed8', roughness: 0.85, flatShading: true }),
  bedLinenGreen: new THREE.MeshStandardMaterial({ color: '#15803d', roughness: 0.85, flatShading: true }),
  bedStraw: new THREE.MeshStandardMaterial({ color: '#eab308', roughness: 0.9, flatShading: true }),
  pillowWhite: new THREE.MeshStandardMaterial({ color: '#f8fafc', roughness: 0.8, flatShading: true }),
  floorPlanks: new THREE.MeshStandardMaterial({ color: '#633d1f', roughness: 0.85, flatShading: true }),
  candleGlow: new THREE.MeshBasicMaterial({ color: '#fde047' }),
  candleUnlit: new THREE.MeshStandardMaterial({ color: '#c9bfab', roughness: 0.9, flatShading: true }),
  windowLit: new THREE.MeshBasicMaterial({ color: '#fef08a' }),
  windowUnlit: new THREE.MeshStandardMaterial({ color: '#181e26', roughness: 0.85, flatShading: true }),
  fireplaceCold: new THREE.MeshStandardMaterial({ color: '#241f1a', roughness: 0.95, flatShading: true }),
  bootsLeather: new THREE.MeshStandardMaterial({ color: '#271b12', roughness: 0.9, flatShading: true }),
};
