export const IMMIGRATION_TICK_INTERVAL = 20;

export const DEFAULT_APPROVAL_RATING = 50;
export const MIN_APPROVAL_FOR_IMMIGRATION = 50;
export const HIGH_APPROVAL_THRESHOLD = 70;
export const EXCELLENT_APPROVAL_THRESHOLD = 85;

export const BASE_IMMIGRATION_PROGRESS_DELTA = 1.2;
export const HIGH_APPROVAL_PROGRESS_DELTA = 1.2;
export const EXCELLENT_APPROVAL_PROGRESS_DELTA = 0.8;
export const IMMIGRATION_DECAY_DELTA = 0.5;
export const MAX_IMMIGRATION_PROGRESS = 100;

export const FEMALE_SPAWN_CHANCE = 0.45;
export const DEFAULT_PEASANT_MOVE_SPEED = 1.35;

export const IMMIGRANT_STARTING_HUNGER = 75;
export const IMMIGRANT_STARTING_ENERGY = 85;
export const IMMIGRANT_STARTING_MOOD = 75;
export const IMMIGRANT_STARTING_ALE = 50;
export const IMMIGRANT_STARTING_HYGIENE = 75;

export const IMMIGRANT_THOUGHT_MODIFIER = 15;
export const IMMIGRANT_THOUGHT_DURATION_TICKS = 3000;
