import type { RegionData } from '../types/game';
import { GridMap } from '../engine/grid/GridMap';

export const MAP_SIZE = 256;
export const DEFAULT_MAP_SEED = 1234.56;

export const DEFAULT_REGIONS: RegionData[] = [
  {
    id: 0,
    name: 'Goldhof',
    ukrName: 'Ґольдгоф',
    description: 'Центральні родючі рівнини, багаті луки, помірний ліс. Ідеальне місце для серця королівства.',
    bounds: { minX: 0, maxX: 127, minZ: 0, maxZ: 127 },
    center: [64, 64],
    spawnPoints: GridMap.getPresetSpawnPoints(0),
    owner: 'player',
    lordName: 'Король Болеслав',
    lordTitle: 'Правитель земель',
    heraldryColor: '#f59e0b',
    heraldryIcon: '👑',
    population: 3,
    approval: 80,
    wealth: 50,
    buildingsCount: 2,
    campPosition: [52, 52],
  },
  {
    id: 1,
    name: 'Waldau',
    ukrName: 'Вальдау',
    description: 'Густі дубові та соснові бори, багаті мисливські угіддя та невичерпні запаси деревини.',
    bounds: { minX: 128, maxX: 255, minZ: 0, maxZ: 127 },
    center: [192, 64],
    spawnPoints: GridMap.getPresetSpawnPoints(1),
    owner: 'bot',
    lordName: 'Барон фон Берг',
    lordTitle: 'Лорд-завойовник',
    heraldryColor: '#dc2626',
    heraldryIcon: '⚔️',
    population: 3,
    approval: 75,
    wealth: 40,
    buildingsCount: 2,
    campPosition: [176, 52],
  },
  {
    id: 2,
    name: 'Eichenau',
    ukrName: 'Айхенау',
    description: 'Озерне узбережжя, річкові заплави та родючі ґрунти для пшеничних ланів та млинів.',
    bounds: { minX: 0, maxX: 127, minZ: 128, maxZ: 255 },
    center: [64, 192],
    spawnPoints: GridMap.getPresetSpawnPoints(2),
    owner: 'bot',
    lordName: 'Леді Хільдеґард',
    lordTitle: 'Володарка лісів',
    heraldryColor: '#2563eb',
    heraldryIcon: '🛡️',
    population: 3,
    approval: 82,
    wealth: 60,
    buildingsCount: 2,
    campPosition: [52, 144],
  },
  {
    id: 3,
    name: 'Zweiau',
    ukrName: 'Цвайау',
    description: 'Скелясті височини, гірські вали, багаті поклади каменю та природні рубежі оборони.',
    bounds: { minX: 128, maxX: 255, minZ: 128, maxZ: 255 },
    center: [192, 192],
    spawnPoints: GridMap.getPresetSpawnPoints(3),
    owner: 'unclaimed',
    lordName: 'Вільні землі',
    lordTitle: 'Нейтральна територія',
    heraldryColor: '#64748b',
    heraldryIcon: '🦅',
    population: 0,
    approval: 0,
    wealth: 0,
    buildingsCount: 0,
    campPosition: [176, 176],
  },
];

export const PRESET_BOT_LORDS = [
  {
    id: 'bot-1',
    name: 'Барон фон Берг',
    title: 'Лорд-завойовник',
    color: '#dc2626',
    avatarColor: '#b91c1c',
    peasantColor: '#ef4444',
    heraldryIcon: '⚔️',
  },
  {
    id: 'bot-2',
    name: 'Леді Хільдеґард',
    title: 'Володарка лісів',
    color: '#2563eb',
    avatarColor: '#1d4ed8',
    peasantColor: '#3b82f6',
    heraldryIcon: '🛡️',
  },
  {
    id: 'bot-3',
    name: 'Герцог Вільгельм',
    title: 'Гірський ярл',
    color: '#16a34a',
    avatarColor: '#15803d',
    peasantColor: '#22c55e',
    heraldryIcon: '🦅',
  },
];
