import type { BuildingBlueprint, BuildingType } from '../../types/game';

export const BUILDING_BLUEPRINTS: Record<BuildingType, BuildingBlueprint> = {
  lumberjack_hut: {
    type: 'lumberjack_hut',
    name: 'Хатина лісоруба',
    description: 'Робоче місце лісорубів. Призначені селяни (до 2 осіб) рубають дерева та заповнюють внутрішнє сховище (до 20 деревини). Коли сховище повне, рубка зупиняється.',
    width: 4,
    height: 2,
    cost: { wood: 10 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 20,
    storageCapacity: { wood: 20 },
    health: 220,
    color: '#78350f',
  },
  tent: {
    type: 'tent',
    name: 'Палатка поселенців',
    description: 'Польовий прихисток з одним затишним ліжком для сну монарха або селянина.',
    width: 3,
    height: 2,
    cost: { wood: 5 },
    category: 'housing',
    workSlots: 0,
    bedsCount: 1,
    health: 150,
    color: '#d97706',
  },
  campfire: {
    type: 'campfire',
    name: 'Вогнище поселення',
    description: 'Центр вашого поселення. Збирає поселенців для відпочинку та зігріває ночами.',
    width: 2,
    height: 2,
    cost: { wood: 5 },
    category: 'infrastructure',
    workSlots: 0,
    health: 100,
    color: '#ea580c',
  },
  peasant_house: {
    type: 'peasant_house',
    name: 'Хатина селян',
    description: 'Просторий середньовічний будинок із 2 великими ліжками, кам\'яним каміном та затишним інтер\'єром. Вночі селяни заходять сюди спати, відновлюючи сили.',
    width: 4,
    height: 2,
    cost: { wood: 15 },
    category: 'housing',
    workSlots: 0,
    bedsCount: 2,
    health: 280,
    color: '#a16207',
  },
  manor: {
    type: 'manor',
    name: 'Маєток Лорда',
    description: 'Розкішна резиденція для монарха та шляхти. Підвищує лояльність та авторитет.',
    width: 5,
    height: 4,
    cost: { wood: 60, stone: 40, gold: 50 },
    category: 'housing',
    workSlots: 2,
    health: 600,
    color: '#4338ca',
  },
  stockpile: {
    type: 'stockpile',
    name: 'Склад ресурсів',
    description: 'Місце для зберігання деревини, каменю, зерна, хліба та елю.',
    width: 4,
    height: 2,
    cost: { wood: 10 },
    category: 'infrastructure',
    workSlots: 0,
    maxStorage: 100,
    health: 200,
    color: '#ca8a04',
  },
  market: {
    type: 'market',
    name: 'Ринок поселення',
    description: 'Центр обігу грошей. Селяни купують тут хліб та ель за зароблені монети, повертаючи капітал до вашої скарбниці.',
    width: 4,
    height: 2,
    cost: { wood: 20, stone: 5 },
    category: 'infrastructure',
    workSlots: 1,
    defaultWage: 2,
    health: 220,
    color: '#10b981',
  },
  wheat_farm: {
    type: 'wheat_farm',
    name: 'Пшеничне поле',
    description: 'Ділянка для вирощування зерна на родючому ґрунті.',
    width: 4,
    height: 4,
    cost: { wood: 10 },
    category: 'agriculture',
    workSlots: 3,
    defaultWage: 2,
    health: 150,
    color: '#eab308',
    produces: {
      inputs: {},
      outputs: { wheat: 15 },
      ticksRequired: 100,
    },
  },
  windmill: {
    type: 'windmill',
    name: 'Млин',
    description: 'Перемелює зібрану пшеницю на борошно для пекарні.',
    width: 3,
    height: 3,
    cost: { wood: 35, stone: 15 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    health: 300,
    color: '#d97706',
    produces: {
      inputs: { wheat: 5 },
      outputs: { flour: 5 },
      ticksRequired: 40,
    },
  },
  bakery: {
    type: 'bakery',
    name: 'Пекарня',
    description: 'Випікає поживний хліб із борошна для продажу селянам на ринку.',
    width: 4,
    height: 2,
    cost: { wood: 25, stone: 20 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    health: 280,
    color: '#b45309',
    produces: {
      inputs: { flour: 4, wood: 1 },
      outputs: { bread: 6 },
      ticksRequired: 30,
    },
  },
  brewery: {
    type: 'brewery',
    name: 'Пивоварня',
    description: 'Варить запашний середньовічний ель. Задовольняє жагу та приносить прибуток на ринку.',
    width: 4,
    height: 2,
    cost: { wood: 30, stone: 10 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    health: 260,
    color: '#92400e',
    produces: {
      inputs: { wheat: 4, wood: 1 },
      outputs: { ale: 5 },
      ticksRequired: 50,
    },
  },
  barracks: {
    type: 'barracks',
    name: 'Казарми',
    description: 'Тренує воїнів та зберігає мечі й обладунки для захисту від розбійників.',
    width: 5,
    height: 3,
    cost: { wood: 45, stone: 30 },
    category: 'military',
    workSlots: 3,
    health: 500,
    color: '#991b1b',
  },
  wooden_wall: {
    type: 'wooden_wall',
    name: 'Дерев’яний частокіл',
    description: 'Захисна стіна, що перекриває прохід ворогам.',
    width: 1,
    height: 1,
    cost: { wood: 3 },
    category: 'infrastructure',
    workSlots: 0,
    health: 120,
    color: '#78350f',
  },
  wooden_gate: {
    type: 'wooden_gate',
    name: 'Дерев’яна брама',
    description: 'Прохідна брама для жителів поселення.',
    width: 1,
    height: 1,
    cost: { wood: 6 },
    category: 'infrastructure',
    workSlots: 0,
    health: 150,
    color: '#9a3412',
  },
  stone_wall: {
    type: 'stone_wall',
    name: 'Кам’яна стіна',
    description: 'Міцна фортифікаційна споруда.',
    width: 1,
    height: 1,
    cost: { stone: 6 },
    category: 'infrastructure',
    workSlots: 0,
    health: 400,
    color: '#64748b',
  },
};
